# Generated by Django 5.2.1 on 2025-05-14 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0002_alter_rol_sueldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tasa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cuotas', models.PositiveIntegerField(default=1)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.empleado')),
                ('tipo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.tipoprestamo')),
            ],
        ),
    ]
